apiVersion: v1
kind: Service
metadata:
  name: pseudo-perseus-loadbalancer
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: pseudo-perseus
spec:
  type: LoadBalancer
  loadBalancerIP: 10.156.0.150
  ports:
  - port: 9613
    protocol: TCP
  selector:
    app: pseudo-perseus