apiVersion: v1
kind: Service
metadata:
  name: pseudo-perseus
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: pseudo-perseus
spec:
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - port: 9613
    protocol: TCP
    targetPort: 9613
  selector:
    app: pseudo-perseus